data:
  APPINSIGHTS_INSTRUMENTATIONKEY: OTQyNzA2MTAtZmEwNS00NTIxLWJmMTMtNGJlZWEwMTZmMDYw
  APPLICATIONINSIGHTS_CONNECTION_STRING: SW5zdHJ1bWVudGF0aW9uS2V5PTk0MjcwNjEwLWZhMDUtNDUyMS1iZjEzLTRiZWVhMDE2ZjA2MDtJbmdlc3Rpb25FbmRwb2ludD1odHRwczovL2Vhc3R1cy04LmluLmFwcGxpY2F0aW9uaW5zaWdodHMuYXp1cmUuY29tLw==
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPW5laWdoYm9ybHlzZztBY2NvdW50S2V5PXBhaTcxNHJDRGlodDlsaWd1TVFhV01UUjIxd0JxbFVYRDlncFdiR0FMN0sra2pwMytnYkVuRi9nWmluN0hrT3ZGZHVxd3BBcG10alRZSDdtclJ2cld3PT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
  FUNCTIONS_EXTENSION_VERSION: fjM=
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  MyMongoDBConnectionString: bW9uZ29kYjovL25laWdoYm9ybHljb3Ntb3NkYjp1eVZJbjQzbzUxOE9XNDdDUDFJdTRTbmN3QXliUW9rSmFLc1pFN2gxUU9NNXVTZE5MSk9YOVhYcG1JVGpIODFxOXJOMzhFcjZRRndrdkR6RUd5dWR0Zz09QG5laWdoYm9ybHljb3Ntb3NkYi5tb25nby5jb3Ntb3MuYXp1cmUuY29tOjEwMjU1Lz9zc2w9dHJ1ZSZyZXBsaWNhU2V0PWdsb2JhbGRiJnJldHJ5d3JpdGVzPWZhbHNlJm1heElkbGVUaW1lTVM9MTIwMDAwJmFwcE5hbWU9QG5laWdoYm9ybHljb3Ntb3NkYkA=
apiVersion: v1
kind: Secret
metadata:
  name: neighborlycluster
---
data:
  host.master: bXBHZDRCYTg0QmFIMlVJdGIvZmhUZ2JkZjhteFlicGxUZG9CR1ROaVFLL2RsRkJHclpXS0xnPT0=
  host.function.default: ZklEb0RHREIzUTV1YXNtUjRFNHVVWC9jcUZyNGpPTjdzcUJZclFQdWNjSUJ4MmExd1lQTVRRPT0=
  host.systemKey.default: bXlBVXlXY05lcGRhNmFSM0pvWk9oMnlOR1hrWDV3ckJGSXNhZlZTaEdkc1g4VDAxQlU0SkZRPT0=
  functions.createadvertisement.default: VDhsOXZhOTdzNXFLWmtlY1lNT3VOQlh1YUd6Y2F4Smw4bVBROEpGWDh4ZDU4LzlnQ2E1cHBnPT0=
  functions.deleteadvertisement.default: akxWNHQ3MVZzbXM4MXpuYUMyNWEvUUJCVjFiTWhRcVFxbVIycDU5bzVDNlVXbm5iNDAyTjVBPT0=
  functions.getadvertisement.default: R3I4OXllVjBybGQ0YnpIU2lQaDFRNG8wN0lrVG14NEZoOGZQNE92cVhWSTdjR29ienpwdGhnPT0=
  functions.getadvertisements.default: bE1oRWFPbjRCWWNWZGF2ckM2eHNBYm82Y3lYYjM3U3JvSXJUWmJzR0ZPaXJuclR5THNMM2p3PT0=
  functions.getpost.default: VEY2ZGZHSnUyc2o1dkVUM2xsMk1SaU5XeWRSMDZaWGVoN2hNcFIycjFQQ0YvZDlPdDJrWVVBPT0=
  functions.getposts.default: RnhFOVNZb2o3YWRzakJlRHp2YnNoY1JYb0hPUHAweDlpWHJ2SXh5a2U1b3BGb3RNcEd1VHB3PT0=
  functions.updateadvertisement.default: OFFEazBTUlc1bnh5Q2d2WUlBT0FrT2xNQ3NXNlVJaHpNN0p6OGxCOHFjWHRjRkZ3bTFXMmZBPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-neighborlycluster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neighborlycluster-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: neighborlycluster-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neighborlycluster-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: neighborlycluster-http
spec:
  selector:
    app: neighborlycluster-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighborlycluster-http
  labels:
    app: neighborlycluster-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neighborlycluster-http
  template:
    metadata:
      labels:
        app: neighborlycluster-http
    spec:
      containers:
      - name: neighborlycluster-http
        image: neighborlyappregistry.azurecr.io/neighborlydocker:v1
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-neighborlycluster
        envFrom:
        - secretRef:
            name: neighborlycluster
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: neighborlycluster-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighborlycluster
  labels:
    app: neighborlycluster
spec:
  selector:
    matchLabels:
      app: neighborlycluster
  template:
    metadata:
      labels:
        app: neighborlycluster
    spec:
      containers:
      - name: neighborlycluster
        image: neighborlyappregistry.azurecr.io/neighborlydocker:v1
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: neighborlycluster
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: neighborlycluster-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: neighborlycluster
  labels: {}
spec:
  scaleTargetRef:
    name: neighborlycluster
  triggers:
  - type: eventgridtrigger
    metadata:
      direction: in
      eventHubName: testhub
      connection: Endpoint=sb://udacityneighborly.servicebus.windows.net/;SharedAccessKeyName=allpolicy;SharedAccessKey=LOxUOkN13xN038T1VoSsmaTt4s7vq/+VCzduS5/nH9A=;EntityPath=testhub
---

